language: php
sudo: false

php:
- 7.1
- 7.2
- 7.3

before_install:
- phpenv config-rm xdebug.ini

install:
- composer create-project koriym/php-skeleton app 1.x-dev

script:
- cd app
- composer tests
